package PruebaFiguras;

public class VentanaTodos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTodos
     */
    public VentanaTodos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgTodos = new javax.swing.JDialog();
        lblPerimetroCir = new javax.swing.JLabel();
        lblAreaCir = new javax.swing.JLabel();
        lblPerimetroR = new javax.swing.JLabel();
        lblAreaR = new javax.swing.JLabel();
        lblPerimetroCua = new javax.swing.JLabel();
        lblAreaCua = new javax.swing.JLabel();
        lblPerimetroT = new javax.swing.JLabel();
        lblAreaT = new javax.swing.JLabel();
        lblTipoT = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        dlgCirculo = new javax.swing.JDialog();
        lblAreaCirculo = new javax.swing.JLabel();
        lblPerimetroCirculo = new javax.swing.JLabel();
        btnOkCirculo = new javax.swing.JButton();
        dlgRectangulo = new javax.swing.JDialog();
        lblAreaRectangulo = new javax.swing.JLabel();
        lblPerimetroRectangulo = new javax.swing.JLabel();
        btnOkRectangulo = new javax.swing.JButton();
        dlgTriangulo = new javax.swing.JDialog();
        lblAreaTriangulo = new javax.swing.JLabel();
        lblPerimetroTriangulo = new javax.swing.JLabel();
        lblTipoTriangulo = new javax.swing.JLabel();
        btnOkTriangulo = new javax.swing.JButton();
        dlgCuadrado = new javax.swing.JDialog();
        lblAreaCuadrado = new javax.swing.JLabel();
        lblPerimetroCuadrado = new javax.swing.JLabel();
        btnOkCuadrado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBaseR = new javax.swing.JTextField();
        txtAlturaR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBaseT = new javax.swing.JTextField();
        txtAlturaT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLado = new javax.swing.JTextField();
        btnCalcularR = new javax.swing.JButton();
        btnBorrarR = new javax.swing.JButton();
        btnBorrarCir = new javax.swing.JButton();
        btnCalcularCir = new javax.swing.JButton();
        btnCalcularT = new javax.swing.JButton();
        btnBorrarT = new javax.swing.JButton();
        btnBorrarCua = new javax.swing.JButton();
        bntBorrarCua = new javax.swing.JButton();
        btnCalcularTodos = new javax.swing.JButton();
        btnBorrarTodos = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuCirculo = new javax.swing.JMenuItem();
        mnuRectangulo = new javax.swing.JMenuItem();
        mnuCuadrado = new javax.swing.JMenuItem();
        mnuTriangulo = new javax.swing.JMenuItem();

        lblPerimetroCir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblAreaCir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblPerimetroR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblAreaR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblPerimetroCua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblAreaCua.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblPerimetroT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblAreaT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblTipoT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgTodosLayout = new javax.swing.GroupLayout(dlgTodos.getContentPane());
        dlgTodos.getContentPane().setLayout(dlgTodosLayout);
        dlgTodosLayout.setHorizontalGroup(
            dlgTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTodosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dlgTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAreaCua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPerimetroT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAreaT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dlgTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPerimetroCir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPerimetroR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAreaCir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAreaR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPerimetroCua, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTipoT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(dlgTodosLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgTodosLayout.setVerticalGroup(
            dlgTodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTodosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblPerimetroCir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAreaCir)
                .addGap(33, 33, 33)
                .addComponent(lblPerimetroR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAreaR)
                .addGap(27, 27, 27)
                .addComponent(lblPerimetroCua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAreaCua)
                .addGap(32, 32, 32)
                .addComponent(lblPerimetroT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAreaT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipoT, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addContainerGap())
        );

        lblAreaCirculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblPerimetroCirculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnOkCirculo.setText("Ok");
        btnOkCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkCirculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgCirculoLayout = new javax.swing.GroupLayout(dlgCirculo.getContentPane());
        dlgCirculo.getContentPane().setLayout(dlgCirculoLayout);
        dlgCirculoLayout.setHorizontalGroup(
            dlgCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgCirculoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOkCirculo)
                .addGap(107, 107, 107))
            .addGroup(dlgCirculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAreaCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerimetroCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgCirculoLayout.setVerticalGroup(
            dlgCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCirculoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAreaCirculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPerimetroCirculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnOkCirculo)
                .addContainerGap())
        );

        lblAreaRectangulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblPerimetroRectangulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnOkRectangulo.setText("Ok");
        btnOkRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkRectanguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgRectanguloLayout = new javax.swing.GroupLayout(dlgRectangulo.getContentPane());
        dlgRectangulo.getContentPane().setLayout(dlgRectanguloLayout);
        dlgRectanguloLayout.setHorizontalGroup(
            dlgRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRectanguloLayout.createSequentialGroup()
                .addGroup(dlgRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgRectanguloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAreaRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(lblPerimetroRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(dlgRectanguloLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnOkRectangulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgRectanguloLayout.setVerticalGroup(
            dlgRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRectanguloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblAreaRectangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPerimetroRectangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(btnOkRectangulo)
                .addContainerGap())
        );

        lblAreaTriangulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblPerimetroTriangulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblTipoTriangulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnOkTriangulo.setText("Ok");
        btnOkTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgTrianguloLayout = new javax.swing.GroupLayout(dlgTriangulo.getContentPane());
        dlgTriangulo.getContentPane().setLayout(dlgTrianguloLayout);
        dlgTrianguloLayout.setHorizontalGroup(
            dlgTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTrianguloLayout.createSequentialGroup()
                .addGroup(dlgTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgTrianguloLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnOkTriangulo))
                    .addGroup(dlgTrianguloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAreaTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPerimetroTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTipoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgTrianguloLayout.setVerticalGroup(
            dlgTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgTrianguloLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAreaTriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPerimetroTriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipoTriangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnOkTriangulo)
                .addContainerGap())
        );

        lblAreaCuadrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblPerimetroCuadrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnOkCuadrado.setText("Ok");
        btnOkCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkCuadradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgCuadradoLayout = new javax.swing.GroupLayout(dlgCuadrado.getContentPane());
        dlgCuadrado.getContentPane().setLayout(dlgCuadradoLayout);
        dlgCuadradoLayout.setHorizontalGroup(
            dlgCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCuadradoLayout.createSequentialGroup()
                .addGroup(dlgCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgCuadradoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAreaCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPerimetroCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addGroup(dlgCuadradoLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnOkCuadrado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgCuadradoLayout.setVerticalGroup(
            dlgCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCuadradoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAreaCuadrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPerimetroCuadrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnOkCuadrado)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Todos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Círculo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Radio");

        txtRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRadioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Rectángulo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Base");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Altura");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Triángulo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Base");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Altura");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Cuadrado");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Lado");

        btnCalcularR.setText("Calcular");
        btnCalcularR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularRActionPerformed(evt);
            }
        });

        btnBorrarR.setText("Borrar");
        btnBorrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarRActionPerformed(evt);
            }
        });

        btnBorrarCir.setText("Borrar");
        btnBorrarCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCirActionPerformed(evt);
            }
        });

        btnCalcularCir.setText("Calcular");
        btnCalcularCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCirActionPerformed(evt);
            }
        });

        btnCalcularT.setText("Calcular");
        btnCalcularT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTActionPerformed(evt);
            }
        });

        btnBorrarT.setText("Borrar");
        btnBorrarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTActionPerformed(evt);
            }
        });

        btnBorrarCua.setText("Calcular");
        btnBorrarCua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCuaActionPerformed(evt);
            }
        });

        bntBorrarCua.setText("Borrar");
        bntBorrarCua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBorrarCuaActionPerformed(evt);
            }
        });

        btnCalcularTodos.setText("Calcular Todos");
        btnCalcularTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTodosActionPerformed(evt);
            }
        });

        btnBorrarTodos.setText("Borrar Todos");
        btnBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodosActionPerformed(evt);
            }
        });

        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jMenu1.setText("Cerrar");

        mnuCerrar.setText("Cerrar");
        mnuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCerrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Otros");

        mnuCirculo.setText("Círculo");
        mnuCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCirculoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCirculo);

        mnuRectangulo.setText("Rectángulo");
        mnuRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRectanguloActionPerformed(evt);
            }
        });
        jMenu2.add(mnuRectangulo);

        mnuCuadrado.setText("Cuadrado");
        mnuCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCuadradoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCuadrado);

        mnuTriangulo.setText("Triángulo");
        mnuTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrianguloActionPerformed(evt);
            }
        });
        jMenu2.add(mnuTriangulo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalcularTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBorrarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtAlturaT))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtBaseT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(41, 41, 41)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnCalcularCir)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnBorrarCir)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcularT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrarT)
                                .addGap(58, 58, 58)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBorrarCua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bntBorrarCua))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCalcularR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrarR))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel10))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtLado))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBaseR)
                                        .addComponent(txtAlturaR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaseR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlturaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularR)
                    .addComponent(btnBorrarR)
                    .addComponent(btnBorrarCir)
                    .addComponent(btnCalcularCir))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBaseT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAlturaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularT)
                    .addComponent(btnBorrarT)
                    .addComponent(btnBorrarCua)
                    .addComponent(bntBorrarCua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularTodos)
                    .addComponent(btnBorrarTodos)
                    .addComponent(btnAtras)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRadioActionPerformed

    private void btnCalcularTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTodosActionPerformed
        double Radio    = Double.parseDouble(txtRadio.getText());
        double BaseR    = Double.parseDouble(txtBaseR.getText());
        double AlturaR  = Double.parseDouble(txtAlturaR.getText());
        double BaseT    = Double.parseDouble(txtBaseT.getText());
        double AlturaT  = Double.parseDouble(txtAlturaT.getText());
        double Lado     = Double.parseDouble(txtLado.getText());
        double pCir     = Circulo.calcular_perimetro(Radio);
        double aCir     = Circulo.calcular_area(Radio);
        double pR       = Rectangulo.calcular_perimetro(BaseR, AlturaR);
        double aR       = Rectangulo.calcular_area(BaseR, AlturaR);
        double pT       = Triangulo.calcular_perimetro(BaseT, AlturaT);
        double aT       = Triangulo.calcular_area(BaseT, AlturaT);
        String tipoT    = Triangulo.tipo_triangulo(BaseT, AlturaT);
        double aCua     = Cuadrado.calcular_area(Lado);
        double pCua     = Cuadrado.calcular_perimetro(Lado);
        lblAreaCir.setText("El área del círculo es = " + aCir);
        lblPerimetroCir.setText("El perímetro del círculo es = " + pCir);
        lblAreaR.setText("El área del rectángulo es = " + aR);
        lblPerimetroR.setText("El perímetro del rectángulo es = " + pR);
        lblAreaCua.setText("El área del cuadrado es = " + aCua);
        lblPerimetroCua.setText("El perímetro del cuadrado es = " + pCua);
        lblAreaT.setText("El área del triángulo es = " + aT);
        lblPerimetroT.setText("El perímetro del triángulo es = " + pT);
        lblTipoT.setText(tipoT);
        dlgTodos.setVisible(true);
        dlgTodos.setSize(325,375);
    }//GEN-LAST:event_btnCalcularTodosActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        dlgTodos.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodosActionPerformed
        txtRadio.setText("");
        txtBaseR.setText("");
        txtAlturaR.setText("");
        txtBaseT.setText("");
        txtAlturaT.setText("");
        txtLado.setText("");
    }//GEN-LAST:event_btnBorrarTodosActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        VentanaPrincipal v = new VentanaPrincipal();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBorrarCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCirActionPerformed
        txtRadio.setText("");
    }//GEN-LAST:event_btnBorrarCirActionPerformed

    private void btnBorrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarRActionPerformed
        txtBaseR.setText("");
        txtAlturaR.setText("");
    }//GEN-LAST:event_btnBorrarRActionPerformed

    private void btnBorrarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTActionPerformed
        txtBaseT.setText("");
        txtAlturaT.setText("");
    }//GEN-LAST:event_btnBorrarTActionPerformed

    private void bntBorrarCuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBorrarCuaActionPerformed
        txtLado.setText("");
    }//GEN-LAST:event_bntBorrarCuaActionPerformed

    private void btnCalcularCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCirActionPerformed
        double Radio    = Double.parseDouble(txtRadio.getText());
        double pCir     = Circulo.calcular_perimetro(Radio);
        double aCir     = Circulo.calcular_area(Radio);
        lblAreaCirculo.setText("El área del círculo es = " + aCir);
        lblPerimetroCirculo.setText("El perímetro del círculo es = " + pCir);
        dlgCirculo.setVisible(true);
        dlgCirculo.setSize(300,150);
    }//GEN-LAST:event_btnCalcularCirActionPerformed

    private void btnOkCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkCirculoActionPerformed
        dlgCirculo.dispose();
    }//GEN-LAST:event_btnOkCirculoActionPerformed

    private void btnCalcularRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRActionPerformed
        double BaseR    = Double.parseDouble(txtBaseR.getText());
        double AlturaR  = Double.parseDouble(txtAlturaR.getText());
        double pR       = Rectangulo.calcular_perimetro(BaseR, AlturaR);
        double aR       = Rectangulo.calcular_area(BaseR, AlturaR);
        lblAreaRectangulo.setText("El área del rectángulo es = " + aR);
        lblPerimetroRectangulo.setText("El perímetro del rectángulo es = " + pR);
        dlgRectangulo.setVisible(true);
        dlgRectangulo.setSize(300,150);
    }//GEN-LAST:event_btnCalcularRActionPerformed

    private void btnOkRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkRectanguloActionPerformed
        dlgRectangulo.dispose();
    }//GEN-LAST:event_btnOkRectanguloActionPerformed

    private void btnCalcularTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTActionPerformed
        double BaseT    = Double.parseDouble(txtBaseT.getText());
        double AlturaT  = Double.parseDouble(txtAlturaT.getText());
        double pT       = Triangulo.calcular_perimetro(BaseT, AlturaT);
        double aT       = Triangulo.calcular_area(BaseT, AlturaT);
        String tipoT    = Triangulo.tipo_triangulo(BaseT, AlturaT);
        lblAreaTriangulo.setText("El área del triángulo es = " + aT);
        lblPerimetroTriangulo.setText("El perímetro del triángulo es = " + pT);
        lblTipoTriangulo.setText(tipoT);
        dlgTriangulo.setVisible(true);
        dlgTriangulo.setSize(300,175);
    }//GEN-LAST:event_btnCalcularTActionPerformed

    private void btnOkTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkTrianguloActionPerformed
        dlgTriangulo.dispose();
    }//GEN-LAST:event_btnOkTrianguloActionPerformed

    private void btnBorrarCuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCuaActionPerformed
        double Lado     = Double.parseDouble(txtLado.getText());
        double aCua     = Cuadrado.calcular_area(Lado);
        double pCua     = Cuadrado.calcular_perimetro(Lado);
        lblAreaCuadrado.setText("El área del cuadrado es = " + aCua);
        lblPerimetroCuadrado.setText("El perímetro del cuadrado es = " + pCua);
        dlgCuadrado.setVisible(true);
        dlgCuadrado.setSize(300,150);
    }//GEN-LAST:event_btnBorrarCuaActionPerformed

    private void btnOkCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkCuadradoActionPerformed
        dlgCuadrado.dispose();
    }//GEN-LAST:event_btnOkCuadradoActionPerformed

    private void mnuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_mnuCerrarActionPerformed

    private void mnuCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCirculoActionPerformed
        VentanaCirculo w = new VentanaCirculo();
        w.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuCirculoActionPerformed

    private void mnuRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRectanguloActionPerformed
        VentanaRectangulo r = new VentanaRectangulo();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuRectanguloActionPerformed

    private void mnuCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCuadradoActionPerformed
        VentanaCuadrado c = new VentanaCuadrado();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuCuadradoActionPerformed

    private void mnuTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrianguloActionPerformed
        VentanaTriangulo t = new VentanaTriangulo();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuTrianguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBorrarCua;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBorrarCir;
    private javax.swing.JButton btnBorrarCua;
    private javax.swing.JButton btnBorrarR;
    private javax.swing.JButton btnBorrarT;
    private javax.swing.JButton btnBorrarTodos;
    private javax.swing.JButton btnCalcularCir;
    private javax.swing.JButton btnCalcularR;
    private javax.swing.JButton btnCalcularT;
    private javax.swing.JButton btnCalcularTodos;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnOkCirculo;
    private javax.swing.JButton btnOkCuadrado;
    private javax.swing.JButton btnOkRectangulo;
    private javax.swing.JButton btnOkTriangulo;
    private javax.swing.JDialog dlgCirculo;
    private javax.swing.JDialog dlgCuadrado;
    private javax.swing.JDialog dlgRectangulo;
    private javax.swing.JDialog dlgTodos;
    private javax.swing.JDialog dlgTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAreaCir;
    private javax.swing.JLabel lblAreaCirculo;
    private javax.swing.JLabel lblAreaCua;
    private javax.swing.JLabel lblAreaCuadrado;
    private javax.swing.JLabel lblAreaR;
    private javax.swing.JLabel lblAreaRectangulo;
    private javax.swing.JLabel lblAreaT;
    private javax.swing.JLabel lblAreaTriangulo;
    private javax.swing.JLabel lblPerimetroCir;
    private javax.swing.JLabel lblPerimetroCirculo;
    private javax.swing.JLabel lblPerimetroCua;
    private javax.swing.JLabel lblPerimetroCuadrado;
    private javax.swing.JLabel lblPerimetroR;
    private javax.swing.JLabel lblPerimetroRectangulo;
    private javax.swing.JLabel lblPerimetroT;
    private javax.swing.JLabel lblPerimetroTriangulo;
    private javax.swing.JLabel lblTipoT;
    private javax.swing.JLabel lblTipoTriangulo;
    private javax.swing.JMenuItem mnuCerrar;
    private javax.swing.JMenuItem mnuCirculo;
    private javax.swing.JMenuItem mnuCuadrado;
    private javax.swing.JMenuItem mnuRectangulo;
    private javax.swing.JMenuItem mnuTriangulo;
    private javax.swing.JTextField txtAlturaR;
    private javax.swing.JTextField txtAlturaT;
    private javax.swing.JTextField txtBaseR;
    private javax.swing.JTextField txtBaseT;
    private javax.swing.JTextField txtLado;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}
